package com.dealio.app.ui.builder.ai

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.AutoAwesome
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material.icons.outlined.Psychology
import androidx.compose.material.icons.outlined.TrendingUp
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.ExposedDropdownMenuDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import com.dealio.app.data.api.Project
import com.dealio.app.ui.builder.DealioCard
import com.dealio.app.ui.builder.GradientButton
import com.dealio.app.ui.builder.LoadingState
import com.dealio.app.ui.builder.SectionLabel
import com.dealio.app.ui.builder.StatusColors
import com.dealio.app.ui.builder.SubScreenScaffold
import com.dealio.app.ui.builder.formatINRShort
import com.dealio.app.ui.builder.priceLow
import com.dealio.app.ui.builder.tools.BuilderToolsViewModel
import com.dealio.app.ui.theme.Teal
import com.dealio.app.ui.theme.TextPrimary
import com.dealio.app.ui.theme.TextSecondary

private fun copy(ctx: Context, text: String) {
    (ctx.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager)
        ?.setPrimaryClip(ClipData.newPlainText("Description", text))
    Toast.makeText(ctx, "Copied", Toast.LENGTH_SHORT).show()
}

private fun englishDesc(p: Project): String {
    val configs = p.configurations?.joinToString(" & ") ?: "premium"
    val price = p.priceLow()?.let { "starting ${formatINRShort(it)}" } ?: "at attractive prices"
    val loc = listOfNotNull(p.locality, p.city).joinToString(", ")
    return "Discover exceptional living at ${p.name} by ${p.builderName ?: "a trusted developer"}, located in $loc. Choose from spacious $configs apartments $price. Enjoy world-class amenities and thoughtful design. ${p.status ?: "Now selling"} — book your site visit today."
}

private fun hindiDesc(p: Project): String {
    val configs = p.configurations?.joinToString(" और ") ?: "प्रीमियम"
    val loc = listOfNotNull(p.locality, p.city).joinToString(", ")
    val price = p.priceLow()?.let { "${formatINRShort(it)} से शुरू" } ?: "आकर्षक कीमतों पर"
    return "$loc में स्थित ${p.name} में असाधारण जीवन का अनुभव करें। $configs अपार्टमेंट $price। विश्वस्तरीय सुविधाएं और बेहतरीन डिज़ाइन। आज ही अपनी साइट विज़िट बुक करें।"
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AiAssistantScreen(nav: NavController, vm: BuilderToolsViewModel = viewModel()) {
    val state by vm.state.collectAsStateWithLifecycle()
    val ctx = LocalContext.current
    var tab by remember { mutableIntStateOf(0) }
    var selectedId by remember { mutableStateOf(-1L) }
    var menuOpen by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf(false) }

    SubScreenScaffold("AI Assistant", nav) { inner ->
        if (state.loading) { LoadingState(Modifier.padding(inner)); return@SubScreenScaffold }
        val project = state.projects.firstOrNull { it.id == selectedId } ?: state.projects.firstOrNull()

        Column(
            Modifier.padding(inner).fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(14.dp),
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Box(Modifier.size(40.dp).background(Color(0xFFF1ECFD), RoundedCornerShape(12.dp)), contentAlignment = Alignment.Center) {
                    Icon(Icons.Outlined.Psychology, null, tint = Color(0xFF7C3AED), modifier = Modifier.size(22.dp))
                }
                Spacer(Modifier.width(12.dp))
                Column {
                    Text("AI Intelligence", color = TextPrimary, fontSize = 16.sp, fontWeight = FontWeight.Bold)
                    Text("Pricing insight & SEO listing descriptions", color = TextSecondary, fontSize = 12.sp)
                }
            }

            if (state.projects.isEmpty()) {
                DealioCard { Text("No projects yet. Create a project to use AI tools.", color = TextSecondary, fontSize = 13.sp) }
                return@Column
            }

            // Project selector
            ExposedDropdownMenuBox(expanded = menuOpen, onExpandedChange = { menuOpen = it }) {
                OutlinedTextField(
                    value = project?.name ?: "Select project", onValueChange = {}, readOnly = true,
                    label = { Text("Project") },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(menuOpen) },
                    modifier = Modifier.fillMaxWidth().menuAnchor(),
                    shape = RoundedCornerShape(12.dp),
                    colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = Teal, unfocusedBorderColor = Color(0xFFE3E9F1)),
                )
                DropdownMenu(expanded = menuOpen, onDismissRequest = { menuOpen = false }) {
                    state.projects.forEach { p ->
                        DropdownMenuItem(text = { Text(p.name) }, onClick = { selectedId = p.id; menuOpen = false; generated = false })
                    }
                }
            }

            // Tabs
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf("Price insight", "Description").forEachIndexed { i, label ->
                    val sel = tab == i
                    Box(
                        Modifier.weight(1f).background(if (sel) Teal else Color.White, RoundedCornerShape(10.dp))
                            .clickable { tab = i }.padding(vertical = 9.dp),
                        contentAlignment = Alignment.Center,
                    ) { Text(label, color = if (sel) Color.White else TextSecondary, fontSize = 12.sp, fontWeight = FontWeight.SemiBold) }
                }
            }

            if (project == null) return@Column

            if (tab == 0) {
                val current = project.pricePerSqftFrom
                val recommended = current?.let { it * 1.06 }
                DealioCard {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(Icons.Outlined.TrendingUp, null, tint = Teal, modifier = Modifier.size(17.dp))
                        Spacer(Modifier.width(8.dp))
                        Text("Price analysis", color = TextPrimary, fontSize = 14.sp, fontWeight = FontWeight.Bold)
                    }
                    Spacer(Modifier.height(12.dp))
                    if (current == null) {
                        Text("Add a per-sqft price to this project to get an AI pricing recommendation.", color = TextSecondary, fontSize = 12.sp)
                    } else {
                        Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                            PriceBox("Current", "₹${current.toLong()}/sqft", Color(0xFFF1F4F8), TextPrimary, Modifier.weight(1f))
                            PriceBox("Recommended", "₹${recommended!!.toLong()}/sqft", Color(0xFFE8F6F1), StatusColors.Green, Modifier.weight(1f), "+6.0%")
                        }
                        Spacer(Modifier.height(10.dp))
                        Text(
                            "Comparable projects in ${project.city ?: "this micro-market"} are trading higher on the back of steady demand and limited new supply. A measured ~6% revision keeps you competitive while improving margin.",
                            color = TextSecondary, fontSize = 12.sp, lineHeight = 18.sp,
                        )
                    }
                }
            } else {
                GradientButton(text = "Generate SEO descriptions", icon = Icons.Outlined.AutoAwesome, onClick = { generated = true })
                if (generated) {
                    DescCard("English", englishDesc(project)) { copy(ctx, it) }
                    DescCard("Hindi", hindiDesc(project)) { copy(ctx, it) }
                }
            }
        }
    }
}

@Composable
private fun PriceBox(label: String, value: String, bg: Color, fg: Color, modifier: Modifier, delta: String? = null) {
    Column(modifier.background(bg, RoundedCornerShape(12.dp)).padding(12.dp)) {
        Text(label, color = TextSecondary, fontSize = 11.sp)
        Text(value, color = fg, fontSize = 15.sp, fontWeight = FontWeight.Bold)
        if (delta != null) Text("$delta increase", color = StatusColors.Green, fontSize = 10.sp, fontWeight = FontWeight.SemiBold)
    }
}

@Composable
private fun DescCard(lang: String, text: String, onCopy: (String) -> Unit) {
    DealioCard {
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
            SectionLabel(lang)
            Row(Modifier.clickable { onCopy(text) }, verticalAlignment = Alignment.CenterVertically) {
                Icon(Icons.Outlined.ContentCopy, null, tint = Teal, modifier = Modifier.size(13.dp))
                Spacer(Modifier.width(4.dp))
                Text("Copy", color = Teal, fontSize = 11.sp, fontWeight = FontWeight.SemiBold)
            }
        }
        Spacer(Modifier.height(8.dp))
        Text(text, color = TextSecondary, fontSize = 13.sp, lineHeight = 19.sp)
    }
}
